shifting_list:
  path: /list/{id}
  defaults:  { _controller: "JLMDailyBundle:Shifting:list" }
  methods: [GET]

shifting_list_page:
  path: /list/{id}/page/{page}
  defaults:  { _controller: "JLMDailyBundle:Shifting:list" }
  methods: [GET]

shifting_new:
  path: /new/{id}
  defaults:  { _controller: "JLMDailyBundle:Shifting:new" }
  methods: [GET]
  
shifting_create:
  path: /create/{id}
  defaults:  { _controller: "JLMDailyBundle:Shifting:create" }
  methods: [POST]
  
shifting_edit:
  path: /{id}/edit
  defaults:  { _controller: "JLMDailyBundle:Shifting:edit" }
  methods: [GET]
  
shifting_edittable:
  path: /{id}/edittable
  defaults:  { _controller: "JLMDailyBundle:Shifting:edittable" }
  methods: [GET]
  
shifting_update:
  path: /{id}/update
  defaults:  { _controller: "JLMDailyBundle:Shifting:update" }
  methods: [PUT,POST]
  
shifting_delete:
  path: /{id}/delete
  defaults:  { _controller: "JLMDailyBundle:Shifting:delete" }
  methods: [DELETE,POST,GET]