# Contract

jlm_contract_contract:
    path:   /contract
    defaults:  { _controller: "JLMContractBundle:Contract:index" }
    methods: [GET]
    
jlm_contract_contract_show:
    path:   /contract/{id}/show
    defaults:  { _controller: "JLMContractBundle:Contract:show" }
    methods: [GET]
    
jlm_contract_contract_new:
    path:   /contract/new
    defaults:  { _controller: "JLMContractBundle:Contract:new" }
    methods: [GET]
 
jlm_contract_contract_create:
    path:   /contract/new
    defaults:  { _controller: "JLMContractBundle:Contract:new" }
    methods: [POST]

jlm_contract_contract_edit:
    path:   /contract/{id}/{formName}
    defaults:  { _controller: "JLMContractBundle:Contract:edit" }
    requirements:
      id: edit|stop
    methods: [GET]
    
jlm_contract_contract_update:
    path:   /contract/{id}/{formName}
    defaults:  { _controller: "JLMContractBundle:Contract:edit" }
    requirements:
      id: edit|stop
    methods: [PUT]