services:
    jlm_contract.type.contract_select:
        class: JLM\ContractBundle\Form\Type\ContractSelectType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: jlm_contract_contract_select }



