parameters:
#    jlm_contract.example.class: JLM\ContractBundle\Example

services:
#    jlm_contract.example:
#        class: %jlm_contract.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
