jlm_follow_default_index:
    path:   /follow/
    defaults:  { _controller: "JLMFollowBundle:Default:index" }
    methods: [GET]
    
jlm_follow_default_update:
    path: /follow/update
    defaults:  { _controller: "JLMFollowBundle:Default:update" }
    methods: [GET]