JLM\ProductBundle\Entity\Product:
  getters:
    coefPositive:
      - "True" : { "message": "Le coéficient doit être positif" }
      
JLM\ProductBundle\Entity\ProductCategory:
  parent:
    - Valid: ~
  children:
    - Valid: { traverse: true }
  name:
    - NotNull: ~
    - NotBlank: ~
    - Type: { type: string }
    
JLM\ProductBundle\Entity\Supplier:
  website:
    - Url: ~
    
JLM\ProductBundle\Entity\Stock:
  getters:
    minUnderMax:
      - "True" : { "message": "Le minimum doit être inférieur ou égal au maximum" }