services:
    jlm_core.type.uploaddocument:
        class: JLM\CoreBundle\Form\Type\UploadDocumentType
        tags:
            - { name: form.type, alias: jlm_core_uploaddocument }
    jlm_core.twig.core_extension:
        class: JLM\CoreBundle\Twig\Extension\CoreExtension
        tags:
            - { name: twig.extension }
