services:
    jlm_core.type.uploaddocument:
        class: JLM\CoreBundle\Form\Type\UploadDocumentType
        tags:
            - { name: form.type, alias: jlm_core_uploaddocument }
    jlm_core.twig.core_extension:
        class: JLM\CoreBundle\Twig\Extension\CoreExtension
        tags:
            - { name: twig.extension }
    jlm_core.type.search:
        class: JLM\CoreBundle\Form\Type\SearchType
        tags:
            - { name: form.type, alias: jlm_core_search }
    jlm_core.twig.search_extension:
        class: JLM\CoreBundle\Twig\Extension\SearchExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
            
    jlm_core.doctrine_subscriber:
        class: JLM\CoreBundle\EventListener\DoctrineSubscriber
        arguments: ["@event_dispatcher"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
