parameters:
    jlm_core.model.mail.class: JLM\CoreBundle\Entity\Email
    jlm_core.manager.mail.class: JLM\CoreBundle\Manager\BaseManager
    
services:
    jlm_core.mail_manager:
        class: "%jlm_core.manager.mail.class%"
        arguments: ["%jlm_core.model.mail.class%"]
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setServices ]
            
    jlm_core.type.uploaddocument:
        class: JLM\CoreBundle\Form\Type\UploadDocumentType
        tags:
            - { name: form.type, alias: jlm_core_uploaddocument }
    jlm_core.twig.core_extension:
        class: JLM\CoreBundle\Twig\Extension\CoreExtension
        tags:
            - { name: twig.extension }
            
    jlm_core.twig.bootstrap_extension:
        class: JLM\CoreBundle\Twig\Extension\BootstrapExtension
        tags:
            - { name: twig.extension }
            
    jlm_core.type.search:
        class: JLM\CoreBundle\Form\Type\SearchType
        tags:
            - { name: form.type, alias: jlm_core_search }
            
    jlm_core.type.email:
        class: JLM\CoreBundle\Form\Type\EmailType
        tags:
            - { name: form.type, alias: jlm_core_email }
            
    jlm_core.type.mail:
        class: JLM\CoreBundle\Form\Type\MailType
        tags:
            - { name: form.type, alias: jlm_core_mail }
            
    jlm_core.type.preattachement:
        class: JLM\CoreBundle\Form\Type\PreAttachementType
        tags:
            - { name: form.type, alias: jlm_core_preattachement }            
            
    jlm_core.type.attachement:
        class: JLM\CoreBundle\Form\Type\AttachementType
        tags:
            - { name: form.type, alias: jlm_core_attachement }
            
    jlm_core.twig.search_extension:
        class: JLM\CoreBundle\Twig\Extension\SearchExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
            
    jlm_core.doctrine_subscriber:
        class: JLM\CoreBundle\EventListener\DoctrineSubscriber
        arguments: ["@event_dispatcher"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
