parameters:
#    jlm_installation.example.class: JLM\InstallationBundle\Example

services:
#    jlm_installation.example:
#        class: %jlm_installation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
