imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
        hinclude_default_template: ::hinclude.html.twig
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    #trust_proxy_headers: ~ # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:horizontal_ext.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    assets:
        #jQuery
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.js'
            filters: [?yui_js]
            
        #jQuery UI
        jqueryui_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jqueryui/ui/jquery-ui.js'
                - '%kernel.root_dir%/../vendor/components/jqueryui/ui/i18n/jquery.ui.datepicker-fr.js'
            filters: [?yui_js]
        jqueryui_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/jquery-ui.css'
            filters: [?yui_css,cssrewrite]
        jqueryui_images00: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/animated-overlay.gif'], output: 'images/animated-overlay.gif'}
        jqueryui_images01: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png'], output: 'images/ui-bg_flat_0_aaaaaa_40x100.png'}
        jqueryui_images02: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_flat_75_ffffff_40x100.png'], output: 'images/ui-bg_flat_75_ffffff_40x100.png'}
        jqueryui_images03: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png'], output: 'images/ui-bg_glass_55_fbf9ee_1x400.png'}
        jqueryui_images04: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_glass_65_ffffff_1x400.png'], output: 'images/ui-bg_glass_65_ffffff_1x400.png'}
        jqueryui_images05: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_glass_75_dadada_1x400.png'], output: 'images/ui-bg_glass_75_dadada_1x400.png'}
        jqueryui_images06: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png'], output: 'images/ui-bg_glass_75_e6e6e6_1x400.png'}
        jqueryui_images07: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png'], output: 'images/ui-bg_glass_95_fef1ec_1x400.png'}
        jqueryui_images08: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png'], output: 'images/ui-bg_highlight-soft_75_cccccc_1x100.png'}
        jqueryui_images09: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-icons_222222_256x240.png'], output: 'images/ui-icons_222222_256x240.png'}
        jqueryui_images10: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-icons_2e83ff_256x240.png'], output: 'images/ui-icons_2e83ff_256x240.png'}
        jqueryui_images11: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-icons_454545_256x240.png'], output: 'images/ui-icons_454545_256x240.png'}
        jqueryui_images12: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-icons_888888_256x240.png'], output: 'images/ui-icons_888888_256x240.png'}
        jqueryui_images13: { inputs: ['%kernel.root_dir%/../vendor/components/jqueryui/themes/smoothness/images/ui-icons_cd0a0a_256x240.png'], output: 'images/ui-icons_cd0a0a_256x240.png'}
        
        #Bootstrap
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/js/bootstrap.js'
            filters: [?yui_js]
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/components/bootstrap/css/bootstrap-responsive.css'
            filters: [?yui_css,cssrewrite]
        bootstrap_iconwhite:
            inputs:
                - '%kernel.root_dir%/../vendor/components/bootstrap/img/glyphicons-halflings-white.png'
            output: 'img/glyphicons-halflings-white.png'
        bootstrap_icon:
            inputs:  
                - '%kernel.root_dir%/../vendor/components/bootstrap/img/glyphicons-halflings.png'
            output: 'img/glyphicons-halflings.png'
        
        #Select2
        select2_js:
            inputs:
                - '%kernel.root_dir%/../vendor/ivaynberg/select2/select2.js'
                - '%kernel.root_dir%/../vendor/ivaynberg/select2/select2_locale_fr.js'
            filters: [?yui_js]
        select2_css:
            inputs:
                - '%kernel.root_dir%/../vendor/ivaynberg/select2/select2.css'
                - '%kernel.root_dir%/../vendor/ivaynberg/select2/select2-bootstrap.css'
            filters: [?yui_css,cssrewrite]
        select2_png: { inputs: ['%kernel.root_dir%/../vendor/ivaynberg/select2/select2.png'], output: 'select2.png'}
        select2_x2png: { inputs: ['%kernel.root_dir%/../vendor/ivaynberg/select2/select2x2.png'], output: 'select2x2.png'}
        select2_spinner: { inputs: ['%kernel.root_dir%/../vendor/ivaynberg/select2/select2-spinner.gif'], output: 'select2-spinner.gif'}
        
        #Highstock
        highstock_js:
            inputs:
                - '%kernel.root_dir%/../vendor/nesbert/highstock/highstock.src.js'
            filters: [?yui_js]
    filters:
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
            apply_to: "\.css$"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.js$"
        cssrewrite: ~
        jpegoptim:
            apply_to: "\.jpe?g$"
        optipng:
            apply_to: "\.png$"
            level: 3
            

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        resolve_target_entities:
            JLM\CollectiveHousingBundle\Model\PropertyInterface : JLM\ModelBundle\Entity\Site
            JLM\InstallationBundle\Model\BayInterface : JLM\ModelBundle\Entity\Door
            JLM\InstallationBundle\Model\PartTypeInterface : JLM\ModelBundle\Entity\DoorType
            JLM\ContactBundle\Model\AddressInterface:        JLM\ModelBundle\Entity\Address
            JLM\ContactBundle\Model\CityInterface:           JLM\ModelBundle\Entity\City
            JLM\ContactBundle\Model\CountryInterface:        JLM\ModelBundle\Entity\Country
            JLM\ContactBundle\Model\EmailInterface:          JLM\ContactBundle\Entity\Email
            JLM\ContactBundle\Model\PhoneInterface:          JLM\ContactBundle\Entity\Phone
            JLM\ContactBundle\Model\PhoneRuleInterface:      JLM\ContactBundle\Entity\PhoneRule
            JLM\ContactBundle\Model\ContactInterface:        JLM\ContactBundle\Entity\Contact
            JLM\ContactBundle\Model\ContactDataInterface:    JLM\ContactBundle\Entity\ContactData
            JLM\ContactBundle\Model\ContactAddressInterface: JLM\ContactBundle\Entity\ContactAddress
            JLM\ContactBundle\Model\ContactEmailInterface:   JLM\ContactBundle\Entity\ContactEmail
            JLM\ContactBundle\Model\ContactPhoneInterface:   JLM\ContactBundle\Entity\ContactPhone
            JLM\ContactBundle\Model\CompanyInterface:        JLM\ContactBundle\Entity\Company
            JLM\ContactBundle\Model\CompanyPersonInterface:  JLM\ContactBundle\Entity\CompanyPerson
            JLM\ContactBundle\Model\PersonInterface:         JLM\ModelBundle\Entity\Person
            JLM\TransmitterBundle\Model\AttributionInterface: JLM\TransmitterBundle\Entity\Attribution
            JLM\TransmitterBundle\Model\TransmitterInterface: JLM\TransmitterBundle\Entity\Transmitter

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: JLM\UserBundle\Entity\User
    
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
            
genemu_form:
    date: ~
    select2: ~

            
