imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
        hinclude_default_template: ::hinclude.html.twig
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    #trust_proxy_headers: ~ # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:basic.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
            apply_to: "\.css$"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.js$"
        cssrewrite: ~
        jpegoptim:
            apply_to: "\.jpe?g$"
        optipng:
            apply_to: "\.png$"
            level: 3
    assets:
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery/jquery.js
            output: js/jquery.js
        jqueryui_js:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.core.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.widget.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.mouse.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.position.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.sortable.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.autocomplete.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.datepicker.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.menu.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/i18n/jquery.ui.datepicker-fr.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.effect.js
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/dist/development-bundle/ui/jquery.ui.effect-fade.js
            output: js/jquery-ui.js
        jqueryui_css:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/jquery-ui.css
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/jquery.ui.theme.css
            output: css/jquery-ui.css
        jqueryui_png1:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/animated-overlay.gif
            output: css/images/animated-overlay.gif
        jqueryui_png2:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
            output: css/images/ui-bg_flat_0_aaaaaa_40x100.png
        jqueryui_png3:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
            output: css/images/ui-bg_flat_75_ffffff_40x100.png
        jqueryui_png4:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
            output: css/images/ui-bg_glass_55_fbf9ee_1x400.png
        jqueryui_png5:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
            output: css/images/ui-bg_glass_65_ffffff_1x400.png
        jqueryui_png6:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_glass_75_dadada_1x400.png
            output: css/images/ui-bg_glass_75_dadada_1x400.png
        jqueryui_png7:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
            output: css/images/ui-bg_glass_75_e6e6e6_1x400.png
        jqueryui_png8:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
            output: css/images/ui-bg_glass_95_fef1ec_1x400.png
        jqueryui_png9:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
            output: css/images/ui-bg_highlight-soft_75_cccccc_1x100.png
        jqueryui_png10:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-icons_222222_256x240.png
            output: css/images/ui-icons_222222_256x240.png
        jqueryui_png11:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-icons_2e83ff_256x240.png
            output: css/images/ui-icons_2e83ff_256x240.png
        jqueryui_png12:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-icons_454545_256x240.png
            output: css/images/ui-icons_454545_256x240.png
        jqueryui_png13:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-icons_888888_256x240.png
            output: css/images/ui-icons_888888_256x240.png
        jqueryui_png14:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/jquery-ui/themes/themes/smoothness/images/ui-icons_cd0a0a_256x240.png
            output: css/images/ui-icons_cd0a0a_256x240.png
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
            output: js/boostrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
            output: css/boostrap.css
        glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: fonts/glyphicons-halflings-regular.eot
        glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: fonts/glyphicons-halflings-regular.svg
        glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: fonts/glyphicons-halflings-regular.ttf
        glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: fonts/glyphicons-halflings-regular.woff
        highstock_js:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/highcharts/highstock.src.js
            output: js/highstock.js
        select2_css:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2.css
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2-bootstrap.css
            output: css/select2.css
        select2_js:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2.js
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2_locale_fr.js
            output: js/select2.js
        select2spinner_gif:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2-spinner.gif
            output: css/select2-spinner.gif
        select2_png:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2.png
            output: css/select2.png
        select2x2_png:
            inputs:
                - %kernel.root_dir%/../vendor/kwizer15/select2/select2x2.png
            output: css/select2x2.png


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: JLM\UserBundle\Entity\User
    
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
            
genemu_form:
    date: ~
    select2: ~
    
            
