parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     jlm
    database_user:     jlm
    database_password: Hary_99

    mailer_transport:  smtp
    mailer_host:       192.168.16.2
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            jlmentreprise
