JLMOfficeBundle:
    resource: "@JLMOfficeBundle/Controller/"
    type:     annotation
    prefix:   /office

JLMModelBundle:
    resource: "@JLMModelBundle/Controller/"
    type:     annotation
    prefix:   /model

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
