services:
  jlm_daily.type.intervention_hidden:
    class: JLM\DailyBundle\Form\Type\InterventionHiddenType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: intervention_hidden }
      
  jlm_daily.eventlistener.action_listener:
    class: JLM\DailyBundle\EventListener\DateSearchListener
    arguments: ["@form.factory"]
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelResponse }
      
  jlm_daily.twig.interventioncount_extension:
    class: JLM\DailyBundle\Twig\Extension\InterventionCountExtension
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: twig.extension }
  
  jlm_daily.bill_subscriber:
    class: JLM\DailyBundle\EventListener\BillSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
