JLM\AskBundle\Entity\Ask:
  properties:
    creation:
      - Date: ~
      - NotNull: ~
    maturity:
      - Date: ~
    person:
      - Valid: ~
    ask:
      - NotBlank: ~
  getters:
    creationBeforeMaturity:
      - True: { message: "La date d'échéance doit être ultérieure à la date de la demande" }
      
JLM\AskBundle\Entity\CommunicationMeans:
  properties:
    name:
      - NotBlank: ~
      - NotNull: ~
      - Type: { type: string }

      