parameters:
    jlm_commerce.model.bill.class: JLM\CommerceBundle\Entity\Bill
    jlm_commerce.manager.bill.class: JLM\CommerceBundle\Manager\BillManager
    jlm_commerce.model.billboost.class: JLM\CommerceBundle\Entity\BillBoost
    jlm_commerce.manager.billboost.class: JLM\CoreBundle\Manager\BaseManager
    jlm_commerce.model.quote.class: JLM\CommerceBundle\Entity\Quote
    jlm_commerce.manager.quote.class: JLM\CommerceBundle\Manager\QuoteManager
    jlm_commerce.model.quotevariant.class: JLM\CommerceBundle\Entity\QuoteVariant
    jlm_commerce.manager.quotevariant.class: JLM\CommerceBundle\Manager\QuoteVariantManager

services:
    jlm_commerce.bill_manager:
        class: "%jlm_commerce.manager.bill.class%"
        arguments: ["%jlm_commerce.model.bill.class%"]
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setServices ]
    
    jlm_commerce.quote_manager:
        class: "%jlm_commerce.manager.quote.class%"
        arguments: ["%jlm_commerce.model.quote.class%"]
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setServices ]
            
    jlm_commerce.quotevariant_manager:
        class: "%jlm_commerce.manager.quotevariant.class%"
        arguments: ["%jlm_commerce.model.quotevariant.class%"]
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setServices ]
    
    jlm_commerce.billboost_manager:
        class: "%jlm_commerce.manager.billboost.class%"
        arguments: ["%jlm_commerce.model.billboost.class%"]
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setServices ]