# Bill

bill:
    path:   /bill
    defaults:  { _controller: "JLMCommerceBundle:Bill:index" }
    methods: [GET]
    
bill_page:
    path:   /bill/page/{page}
    defaults:  { _controller: "JLMCommerceBundle:Bill:index" }
    methods: [GET]
    
bill_listinseizure:
    path:   /bill/inseizure
    defaults:  { _controller: "JLMCommerceBundle:Bill:listinseizure" }
    methods: [GET]
    
bill_listinseizure_page:
    path:   /bill/inseizure/page/{page}
    defaults:  { _controller: "JLMCommerceBundle:Bill:listinseizure" }
    methods: [GET]
    
bill_listsended:
    path:   /bill/sended
    defaults:  { _controller: "JLMCommerceBundle:Bill:listsended" }
    methods: [GET]
    
bill_listsended_page:
    path:   /bill/sended/page/{page}
    defaults:  { _controller: "JLMCommerceBundle:Bill:listsended" }
    methods: [GET]
    
bill_listpayed:
    path:   /bill/payed
    defaults:  { _controller: "JLMCommerceBundle:Bill:listpayed" }
    methods: [GET]
    
bill_listpayed_page:
    path:   /bill/payed/page/{page}
    defaults:  { _controller: "JLMCommerceBundle:Bill:listpayed" }
    methods: [GET]
    
bill_listcanceled:
    path:   /bill/canceled
    defaults:  { _controller: "JLMCommerceBundle:Bill:listcanceled" }
    methods: [GET]
    
bill_listcanceled_page:
    path:   /bill/canceled/page/{page}
    defaults:  { _controller: "JLMCommerceBundle:Bill:listcanceled" }
    methods: [GET]

bill_show:
    path:   /bill/{id}/show
    defaults:  { _controller: "JLMCommerceBundle:Bill:show" }
    methods: [GET]
    
bill_new:
    path:   /bill/new
    defaults:  { _controller: "JLMCommerceBundle:Bill:new" }
    methods: [GET]
    
bill_new_door:
    path:   /bill/new/door/{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:newdoor" }
    methods: [GET]
    
bill_new_quotevariant:
    path:   /bill/new/quote/{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:newquote" }
    methods: [GET]
    
bill_new_intervention:
    path:   /bill/new/intervention/{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:newintervention" }
    methods: [GET]
    
bill_create:
    path:   /bill/create
    defaults:  { _controller: "JLMCommerceBundle:Bill:create" }
    methods: [POST]
    
bill_edit:
    path:   /bill/{id}/edit
    defaults:  { _controller: "JLMCommerceBundle:Bill:edit" }
    methods: [GET]
    
bill_update:
    path:   /bill/{id}/update
    defaults:  { _controller: "JLMCommerceBundle:Bill:update" }
    methods: [POST]
    
bill_print:
    path:   /bill/{id}/print
    defaults:  { _controller: "JLMCommerceBundle:Bill:print" }
    methods: [GET]
    
bill_printduplicate:
    path:   /bill/{id}/printduplicate
    defaults:  { _controller: "JLMCommerceBundle:Bill:printduplicate" }
    methods: [GET]
    
bill_printlist:
    path:   /bill/printlist
    defaults:  { _controller: "JLMCommerceBundle:Bill:printlist" }
    methods: [GET]
    
bill_printboost:
    path:   /bill/{id}/printboost
    defaults:  { _controller: "JLMCommerceBundle:Bill:printboost" }
    methods: [GET]
    
bill_ready:
    path:   /bill/{id}/ready
    defaults:  { _controller: "JLMCommerceBundle:Bill:ready" }
    methods: [GET]
    
bill_send:
    path:   /bill/{id}/send
    defaults:  { _controller: "JLMCommerceBundle:Bill:send" }
    methods: [GET]
    
bill_cancel:
    path:   /bill/{id}/cancel
    defaults:  { _controller: "JLMCommerceBundle:Bill:cancel" }
    methods: [GET]
    
bill_back:
    path:   /bill/{id}/back
    defaults:  { _controller: "JLMCommerceBundle:Bill:back" }
    methods: [GET]
    
bill_payed:
    path:   /bill/{id}/payed
    defaults:  { _controller: "JLMCommerceBundle:Bill:payed" }
    methods: [GET]
    
bill_sidebar:
    path:   /bill/sidebar
    defaults:  { _controller: "JLMCommerceBundle:Bill:sidebar" }
    methods: [GET]
    
bill_todo:
    path:   /bill/todo
    defaults:  { _controller: "JLMCommerceBundle:Bill:todo" }
    methods: [GET]
    
bill_toboost:
    path:   /bill/toboost
    defaults:  { _controller: "JLMCommerceBundle:Bill:toboost" }
    methods: [GET]
    
bill_boostok:
    path:   /bill/{id}/boostok
    defaults:  { _controller: "JLMCommerceBundle:Bill:boostok" }
    methods: [GET]
    
bill_search:
    path:   /bill/search
    defaults:  { _controller: "JLMCommerceBundle:Bill:search" }
    methods: [POST]
    

# Quote
quote:
    path: /quote
    defaults: { _controller: "JLMCommerceBundle:Quote:index" }
    methods: [GET]
    
quote_page:
    path: /quote/page/{page}
    defaults: { _controller: "JLMCommerceBundle:Quote:index" }
    methods: [GET]
    
quote_state:
    path: /quote/page/{page}/state/{state}
    defaults: { _controller: "JLMCommerceBundle:Quote:index" }
    methods: [GET]
    
quote_show:
    path: /quote/{id}/show
    defaults: { _controller: "JLMCommerceBundle:Quote:show" }
    methods: [GET]
    
quote_newfromask:
    path: /quote/new/fromask/{id}
    defaults: { _controller: "JLMCommerceBundle:Quote:new" }
    methods: [GET]
    
quote_create:
    path: /quote/create
    defaults: { _controller: "JLMCommerceBundle:Quote:create" }
    methods: [POST]
    
quote_edit:
    path: /quote/{id}/edit
    defaults: { _controller: "JLMCommerceBundle:Quote:edit" }
    methods: [GET]
    
quote_update:
    path: /quote/{id}/update
    defaults: { _controller: "JLMCommerceBundle:Quote:update" }
    methods: [POST]
    
quote_delete:
    path: /quote/{id}/delete
    defaults: { _controller: "JLMCommerceBundle:Quote:delete" }
    methods: [POST]
    
quote_search:
    path: /quote/search
    defaults: { _controller: "JLMCommerceBundle:Quote:search" }
    methods: [POST]
    
quote_print:
    path: /quote/{id}/print
    defaults: { _controller: "JLMCommerceBundle:Quote:print" }
    methods: [GET]
    
quote_jacket:
    path: /quote/{id}/jacket
    defaults: { _controller: "JLMCommerceBundle:Quote:jacket" }
    methods: [GET]
    
quote_mail:
    path: /quote/{id}/mail
    defaults: { _controller: "JLMCommerceBundle:Quote:mail" }
    methods: [GET]
    
quote_sendmail:
    path: /quote/{id}/sendmail
    defaults: { _controller: "JLMCommerceBundle:Quote:sendmail" }
    methods: [POST]
    
    
# QuoteVariant
variant_new:
    path: /quote/variant/{id}/new
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:new" }
    methods: [GET]
    
variant_create:
    path: /quote/variant/create
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:create" }
    methods: [POST]
    
variant_edit:
    path: /quote/variant/{id}/edit
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:edit" }
    methods: [GET]
    
variant_update:
    path: /quote/variant/{id}/update
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:update" }
    methods: [POST]
    
variant_ready:
    path: /quote/variant/{id]/ready
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:ready" }
    methods: [GET]
    
variant_mail:
    path: /quote/variant/{id}/mail
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:mail" }
    methods: [GET]
    
variant_sendmail:
    path: /quote/variant/{id}/sendmail
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:sendmail" }
    methods: [POST]
    
variant_print:
    path: /quote/variant/{id}/print
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:print" }
    methods: [GET]
    
variant_printcoding:
    path: /quote/variant/{id}/printcoding
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:printcoding" }
    methods: [GET]
    
variant_unvalid:
    path: /quote/variant/{id}/unvalid
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:unvalid" }
    methods: [GET]
    
variant_fax:
    path: /quote/variant/{id}/fax
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:fax" }
    methods: [GET]
    
variant_cancel:
    path: /quote/variant/{id}/cancel
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:cancel" }
    methods: [GET]
    
variant_receipt:
    path: /quote/variant/{id}/receipt
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:receipt" }
    methods: [GET]
    
variant_oldgiven:
    path: /quote/variant/{id}/oldgiven
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:oldgiven" }
    methods: [GET]
    
variant_given:
    path: /quote/variant/{id}/given
    defaults: { _controller: "JLMCommerceBundle:QuoteVariant:given" }
    methods: [GET]


