services:   
    jlm_commerce.listener.billnumbergenerator_listener:
        class: JLM\CommerceBundle\EventListener\BillNumberGenerator
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
    jlm_commerce.listener.quotenumbergenerator_listener:
        class: JLM\CommerceBundle\EventListener\QuoteNumberGenerator
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
    jlm_commerce.bill_subscriber:
        class: JLM\CommerceBundle\EventListener\BillSubscriber
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_subscriber }
            
    jlm_commerce.quotevariant_subscriber:
        class: JLM\CommerceBundle\EventListener\QuoteVariantSubscriber
        arguments: ["@doctrine.orm.entity_manager","@mailer"]
        tags:
            - { name: kernel.event_subscriber }
            
    jlm_commerce.event_subscriber:
        class: JLM\CommerceBundle\EventListener\EventSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }
      
    jlm_commerce.event_subscriber:
        class: JLM\CommerceBundle\EventListener\BillBoostSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

