JLM\UserBundle\Entity\User:
  type: entity 
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  oneToOne:
    contact:
      targetEntity: JLM\ContactBundle\Model\ContactInterface