JLM\OfficeBundle\Entity\OrderLine:
  type: entity
  table: order_lines
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    position:
      type: smallint
      nullable: true
    reference:
      nullable: true
    designation: ~
    quantity:
      type: integer
  manyToOne:
    order:
      targetEntity: JLM\OfficeBundle\Entity\Order
      inversedBy: lines
      