services:
  jlm_follow.quotevariant_subscriber:
    class: JLM\FollowBundle\EventListener\QuoteVariantSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
      
  jlm_follow.intervention_subscriber:
    class: JLM\FollowBundle\EventListener\InterventionSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
      
  jlm_follow.order_subscriber:
    class: JLM\FollowBundle\EventListener\OrderSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
      
  jlm_follow.work_subscriber:
    class: JLM\FollowBundle\EventListener\WorkSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }