jlm_contact_rest_city_search:
    path:   /cities.json
    defaults:  { _controller: "JLMContactBundle:City:search" }
    methods: [GET]
    
jlm_contact_rest_city_get:
    path:   /city.json
    defaults:  { _controller: "JLMContactBundle:City:json" }
    methods: [GET]
    
jlm_contact_ajax_person_show:
    path: /person/ajax/{id}/show
    defaults:  { _controller: "JLMContactBundle:AjaxPerson:showajax" }
    methods: [GET]
   
jlm_contact_ajax_person_new:
    path: /person/ajax/new
    defaults:  { _controller: "JLMContactBundle:AjaxPerson:newajax" }
    methods: [GET]
    
jlm_contact_ajax_person_create:
    path: /person/ajax/create
    defaults:  { _controller: "JLMContactBundle:AjaxPerson:createajax" }
    methods: [POST]
    
jlm_contact_ajax_person_autocomplete:
    path: /person/ajax/autocomplete
    defaults: { _controller: "JLMContactBundle:AjaxPerson:autocomplete" }
    methods: [POST]

jlm_contact_contact_list:
    path: /contact
    defaults: { _controller: "JLMContactBundle:Contact:list" }
    methods: [GET]

jlm_contact_contact_new:
    path: /{id}/new
    defaults: { _controller: "JLMContactBundle:Contact:edit" }
    requirements:
      id: person|company|association
    methods: [GET, POST]

jlm_contact_contact_edit:
    path: /{id}/edit
    defaults: { _controller: "JLMContactBundle:Contact:edit" }
    requirements:
      id: \d+
    methods: [GET, PUT]
    

jlm_contact_contact_show:
    path: /{id}
    defaults: { _controller: "JLMContactBundle:Contact:show" }
    methods: [GET]
