parameters:
#    jlm_contact.example.class: JLM\ContactBundle\Example

services:
#    jlm_contact.example:
#        class: %jlm_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
