services:
    jlm_contact.type.city_select:
        class: JLM\ContactBundle\Form\Type\CitySelectType
        tags:
            - { name: form.type, alias: jlm_contact_city_select }
    jlm_contact.type.address:
        class: JLM\ContactBundle\Form\Type\AddressType
        tags:
            - { name: form.type, alias: jlm_contact_address }