JLM\ContactBundle\Entity\Country:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - Type: { type: string }
            - Length: { min: 2, max: 2 }
            - NotBlank: ~

JLM\ContactBundle\Entity\City:
    properties:
        zip:
            - Type: { type: string }
            - Length: { min: 4, max: 20 }
            - NotNull: ~
        country:
            - NotNull: ~
            - Valid: ~
            
JLM\ContactBundle\Entity\Address:
    properties:
        street:
            - Type: { type: string }
        city:
            - NotNull: ~
            - Valid: ~
