services:
  jlm_office.askquote_manager:
    class: JLM\CoreBundle\Manager\BaseManager
    arguments: ["JLM\OfficeBundle\Entity\AskQuote"]
    calls:
      - [ setContainer, ["@service_container"]]
      - [ setServices ]
  
  jlm_office.twig.askquotecount_extension:
    class: JLM\OfficeBundle\Twig\Extension\AskQuoteCountExtension
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: twig.extension }
  
  jlm_office.twig.ordercount_extension:
    class: JLM\OfficeBundle\Twig\Extension\OrderCountExtension
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: twig.extension }
  
  jlm_office.type.order_line:
    class: JLM\OfficeBundle\Form\Type\OrderLineType
    tags:
      - { name: form.type, alias: order_line }
  
  jlm_office.type.askquote_hidden:
    class: JLM\OfficeBundle\Form\Type\AskQuoteHiddenType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: askquote_hidden }
  
  jlm_office.quote_subscriber:
    class: JLM\OfficeBundle\EventListener\QuoteSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
      