JLM\ContactBundle\Entity\City:
  type: entity
  table: jlm_contact_city
  repositoryClass: JLM\ContactBundle\Repository\CityRepository
  readOnly: true
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    zip:
      type: string
      length: 20
  manyToOne:
    country:
      targetEntity: JLM\ContactBundle\Entity\Country
      joinColumn: 
        name: country_code
        referencedColumnName: code
    