JLM\ContactBundle\Entity\Company:
    type: entity
    table: jlm_contact_company
    fields:
        siren:
            type: string
        nic:
            type: string
    manyToMany:
        contacts:
            targetEntity: JLM\ContactBundle\Model\CompanyPersonInterface
            mappedBy: company