JLM\ContactBundle\Entity\Company:
  type: entity
  table: companies
  inheritanceType: JOINED
  discriminatorColumn:
    name: discr
    type: string
  discriminatorMap:
    trustee: JLM\ModelBundle\Entity\Trustee
    supplier: JLM\ModelBundle\Entity\Supplier
    company: Company
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
    