JLM\ContactBundle\Entity\Contact:
  type: entity
  table: jlm_contact_contact
  inheritanceType: JOINED
  discriminatorColumn:
    name: discr
    type: string
  discriminatorMap:
    person: JLM\ContactBundle\Entity\Person
    company: JLM\ContactBundle\Entity\Company
    association: JLM\ContactBundle\Entity\Association
  id:
    id:
      type: integer
      nullable: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    email:
      type: string
      nullable: true
  oneToMany:
    phones:
      targetEntity: JLM\ContactBundle\Entity\ContactPhone
      mappedBy: contact
  oneToOne:
    address:
      targetEntity: JLM\ContactBundle\Model\AddressInterface
    