JLM\ContactBundle\Entity\ContactDecorator:
  type: mappedSuperclass
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    contact:
      targetEntity: JLM\ContactBundle\Model\ContactInterface
      cascade: ["persist"]
      joinColumn:
        name: contact_id
        referencedColumnName: id
    