JLM\ContactBundle\Entity\Contact:
    type: entity
    table: jlm_contact_contact
    inheritanceType: JOINED
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        person: Person
        company: Company
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
    oneToMany:
        datas:
            targetEntity: JLM\ContactBundle\Model\ContactDataInterface
            mappedBy: contact
                