JLM\ContactBundle\Entity\ContactPhone:
  type: entity
  table: jlm_contact_contact_phone
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    label: ~
  oneToOne:
    phone:
      targetEntity: JLM\ContactBundle\Model\PhoneInterface
  manyToOne:
    contact:
      targetEntity: JLM\ContactBundle\Entity\Contact
      inversedBy: phones
  
    