JLM\ContactBundle\Entity\ContactDecorator:
    type: mappedSuperclass
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        contact:
            targetEntity: JLM\ContactBundle\Model\ContactInterface
        