JLM\ContactBundle\Entity\CorporationContact:
  type: entity
  table: jlm_contact_corporationcontact
  fields:
    position:
      type: string
  manyToOne:
    corporation:
      targetEntity: JLM\ContactBundle\Model\CorporationInterface
    
    