JLM\ContactBundle\Entity\Person:
  type: entity
  table: jlm_contact_person
  repositoryClass: JLM\ContactBundle\Repository\PersonRepository
  fields:
    title:
      type: string
      length: 4
    firstName:
      type: string
      nullable: true
    lastName:
      type: string
  lifecycleCallbacks:
    prePersist: [ attributeName ]
    preUpdate: [ attributeName ]
    