services:
  \JLM\ModelBundle\Form\Type\DistanceType:
    class: JLM\ModelBundle\Form\Type\DistanceType
    tags:
      - { name: form.type, alias: distance }
      
  \JLM\ModelBundle\Form\Type\DatepickerType:
    class: JLM\ModelBundle\Form\Type\DatepickerType
    tags:
      - { name: form.type, alias: datepicker }
      
  \JLM\ModelBundle\Form\Type\TrusteeSelectType:
    class: JLM\ModelBundle\Form\Type\TrusteeSelectType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: trustee_select }
      
  \JLM\ModelBundle\Form\Type\SiteSelectType:
    class: JLM\ModelBundle\Form\Type\SiteSelectType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: site_select }
      
  \JLM\ModelBundle\Form\Type\DoorHiddenType:
    class: JLM\ModelBundle\Form\Type\DoorHiddenType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: door_hidden }
      
  \JLM\ModelBundle\Form\Type\SiteContactHiddenType:
    class: JLM\ModelBundle\Form\Type\SiteContactHiddenType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: sitecontact_hidden }
      
  \JLM\ModelBundle\Form\Type\TrusteeHiddenType:
    class: JLM\ModelBundle\Form\Type\TrusteeHiddenType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: trustee_hidden }
      
  \JLM\ModelBundle\Form\Type\DoorSelectType:
    class: JLM\ModelBundle\Form\Type\DoorSelectType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: door_select }
      
  \JLM\ModelBundle\Form\Type\SiteHiddenType:
    class: JLM\ModelBundle\Form\Type\SiteHiddenType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: site_hidden }
      
  jlm_model.email_subscriber:
    class: JLM\ModelBundle\EventListener\EmailSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
      
  jlm_model.bill_subscriber:
    class: JLM\ModelBundle\EventListener\BillSubscriber
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }
      
  