services:
    jlm_front.form.type.contact:
        class: JLM\FrontBundle\Form\Type\ContactType
        tags:
            - { name: form.type, alias: jlm_front_contacttype }

    jlm_front.form.type.askquote:
        class: JLM\FrontBundle\Form\Type\AskQuoteType
        tags:
            - { name: form.type, alias: jlm_front_askquotetype }