JLM\CommerceBundle\Entity\BillBoost:
  type: entity
  table: jlm_commerce_boost_bill
  repositoryClass: JLM\CommerceBundle\Repository\BillBoostRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    bill:
      targetEntity: JLM\CommerceBundle\Model\BillInterface
          