JLM\CommerceBundle\Entity\VAT:
  type: entity
  table: vat
  readOnly: true
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    rate:
      type: decimal
      precision: 3
      scale: 3


    