bill:
    path:   /
    defaults:  { _controller: "JLMCommerceBundle:Bill:index" }
    methods: [GET]

bill_show:
    path:   /{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:show" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_new:
    path:   /new
    defaults:  { _controller: "JLMCommerceBundle:Bill:new" }
    methods: [GET]
    
bill_new_door:
    path:   /new/door/{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:newdoor" }
    methods: [GET]
    
bill_new_quotevariant:
    path:   /new/quote/{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:newquote" }
    methods: [GET]
    
bill_new_intervention:
    path:   /new/intervention/{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:newintervention" }
    methods: [GET]
    
bill_create:
    path:   /create
    defaults:  { _controller: "JLMCommerceBundle:Bill:create" }
    methods: [POST]
    
bill_edit:
    path:   /{id}/edit
    defaults:  { _controller: "JLMCommerceBundle:Bill:edit" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_update:
    path:   /{id}/update
    defaults:  { _controller: "JLMCommerceBundle:Bill:update" }
    requirements:
        id: \d+
    methods: [POST]
    
bill_print:
    path:   /{id}/print
    defaults:  { _controller: "JLMCommerceBundle:Bill:print" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_printduplicate:
    path:   /{id}/printduplicate
    defaults:  { _controller: "JLMCommerceBundle:Bill:printduplicate" }
    methods: [GET]
    
bill_printlist:
    path:   /printlist
    defaults:  { _controller: "JLMCommerceBundle:Bill:printlist" }
    methods: [GET]
    
bill_printboost:
    path:   /{id}/printboost
    defaults:  { _controller: "JLMCommerceBundle:Bill:printboost" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_ready:
    path:   /{id}/ready
    defaults:  { _controller: "JLMCommerceBundle:Bill:ready" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_send:
    path:   /{id}/send
    defaults:  { _controller: "JLMCommerceBundle:Bill:send" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_cancel:
    path:   /{id}/cancel
    defaults:  { _controller: "JLMCommerceBundle:Bill:cancel" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_back:
    path:   /{id}/back
    defaults:  { _controller: "JLMCommerceBundle:Bill:back" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_payed:
    path:   /{id}/payed
    defaults:  { _controller: "JLMCommerceBundle:Bill:payed" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_sidebar:
    path:   /sidebar
    defaults:  { _controller: "JLMCommerceBundle:Bill:sidebar" }
    methods: [GET]
    
bill_todo:
    path:   /todo
    defaults:  { _controller: "JLMCommerceBundle:Bill:todo" }
    methods: [GET]
    
bill_toboost:
    path:   /toboost
    defaults:  { _controller: "JLMCommerceBundle:Bill:toboost" }
    methods: [GET]
    
bill_boostok:
    path:   /{id}/boostok
    defaults:  { _controller: "JLMCommerceBundle:Bill:boostok" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_search:
    path:   /search
    defaults:  { _controller: "JLMCommerceBundle:Bill:search" }
    methods: [GET]
    