bill:
    path:   /
    defaults:  { _controller: "JLMCommerceBundle:Bill:index" }
    methods: [GET]

bill_show:
    path:   /{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:show" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_new:
    path:   /new
    defaults:  { _controller: "JLMCommerceBundle:Bill:new" }
    methods: [GET]
    
bill_create:
    path:   /
    defaults:  { _controller: "JLMCommerceBundle:Bill:new" }
    methods: [POST]
    
bill_edit:
    path:   /{id}/edit
    defaults:  { _controller: "JLMCommerceBundle:Bill:edit" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_update:
    path:   /{id}
    defaults:  { _controller: "JLMCommerceBundle:Bill:edit" }
    requirements:
        id: \d+
    methods: [PUT,POST]
    
bill_print:
    path:   /{id}/print/{duplicate}
    defaults:
      _controller: "JLMCommerceBundle:Bill:print"
      duplicate: normal
    requirements:
      id: \d+
      duplicate: normal|duplicata
    methods: [GET]
    
bill_printduplicate:
    path:   /{id}/printduplicate/{duplicate}
    defaults:
      _controller: "JLMCommerceBundle:Bill:print"
      duplicate: duplicata
    requirements:
      id: \d+
      duplicate: normal|duplicata
    methods: [GET]
    
bill_printlist:
    path:   /printlist
    defaults:  { _controller: "JLMCommerceBundle:Bill:printlist" }
    methods: [GET]
    
#bill_printboost:
#    path:   /{id}/printboost
#    defaults:  { _controller: "JLMCommerceBundle:Bill:printboost" }
#    requirements:
#        id: \d+
#    methods: [GET]
    
bill_ready:
    path:   /{id}/ready
    defaults:  { _controller: "JLMCommerceBundle:Bill:ready" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_send:
    path:   /{id}/send
    defaults:  { _controller: "JLMCommerceBundle:Bill:send" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_cancel:
    path:   /{id}/cancel
    defaults:  { _controller: "JLMCommerceBundle:Bill:cancel" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_back:
    path:   /{id}/back
    defaults:  { _controller: "JLMCommerceBundle:Bill:back" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_payed:
    path:   /{id}/payed
    defaults:  { _controller: "JLMCommerceBundle:Bill:payed" }
    requirements:
        id: \d+
    methods: [GET]
    
bill_sidebar:
    path:   /sidebar
    defaults:  { _controller: "JLMCommerceBundle:Bill:sidebar" }
    methods: [GET]
    
bill_todo:
    path:   /todo
    defaults:  { _controller: "JLMCommerceBundle:Bill:todo" }
    methods: [GET]
    
#bill_toboost:
#    path:   /toboost
#    defaults:  { _controller: "JLMCommerceBundle:Bill:toboost" }
#    methods: [GET]
#    
#bill_boostok:
#    path:   /{id}/boostok
#    defaults:  { _controller: "JLMCommerceBundle:Bill:boostok" }
#    requirements:
#        id: \d+
#    methods: [GET]
    
bill_search:
    path:   /search
    defaults:  { _controller: "JLMCommerceBundle:Bill:search" }
    methods: [GET]
 
#jlm_commerce_bill_boostemail:
#    path: /boost/{id}/email
#    defaults:
#        _controller: JLMCommerceBundle:Bill:boostemail
#    methods: [GET,POST]

    
    
