quote:
    path: /
    defaults: { _controller: "JLMCommerceBundle:Quote:index" }
    methods: [GET]
    
quote_show:
    path: /{id}
    defaults: { _controller: "JLMCommerceBundle:Quote:show" }
    requirements:
        id: \d+
    methods: [GET]
    
quote_new:
    path: /new
    defaults: { _controller: "JLMCommerceBundle:Quote:new" }
    methods: [GET]
    
quote_create:
    path: /
    defaults: { _controller: "JLMCommerceBundle:Quote:new" }
    requirements:
        id: \d+
    methods: [POST]
    
quote_edit:
    path: /{id}/edit
    defaults: { _controller: "JLMCommerceBundle:Quote:edit" }
    requirements:
        id: \d+
    methods: [GET]
    
quote_update:
    path: /{id}
    defaults: { _controller: "JLMCommerceBundle:Quote:edit" }
    requirements:
        id: \d+
    methods: [PUT,POST]
    
quote_search:
    path: /search
    defaults: { _controller: "JLMCommerceBundle:Quote:search" }
    methods: [GET]
    
quote_print:
    path: /{id}/print
    defaults: { _controller: "JLMCommerceBundle:Quote:print" }
    requirements:
        id: \d+
    methods: [GET]
    
quote_jacket:
    path: /{id}/jacket
    defaults: { _controller: "JLMCommerceBundle:Quote:jacket" }
    requirements:
        id: \d+
    methods: [GET]
    
quote_mail:
    path: /{id}/mail
    defaults: { _controller: "JLMCommerceBundle:Quote:sendByMail" }
    requirements:
        id: \d+
    methods: [GET|POST]
    
jlm_commerce_quote_variant:
    resource: "@JLMCommerceBundle/Resources/config/routing/quote_variant.yml"
    prefix:   /variant
 
